type token = 
    EOF
  | BOOLEAN | BREAK | CLASS | CONTINUE
  | ELSE | EXTENDS | FLOAT | DEFAULT
  | INT | NEW | IF | PUBLIC
  | RETURN | STATIC | WHILE | THIS
  | NULL_LITERAL | LPAREN | RPAREN | LBRACE | RBRACE
  | LBRACK | RBRACK | SEMICOLON | COMMA | DOT
  | EQ | LT | GT | EQEQ | LTEQ | GTEQ
  | NOT | COLON | ANDAND | OROR
  | PLUS | MINUS | MULT | DIV | AND | OR
  | INTEGER_LITERAL of int
  | FLOAT_LITERAL of float
  | BOOLEAN_LITERAL of bool
  | IDENTIFIER of string
  | STRING_LITERAL of string
  | JAVADOC of string
